name: Branch Name and Code Review Validation
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  branchNameAndCodeReviewValidation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch Name
        run: |
          branch_name=$(echo "${{ github.head_ref }}" | awk -F '/' '{print $NF}')
          if [[ ! "$branch_name" =~ ^(PI)-[0-9]+$ ]]; then
            echo "Invalid branch name format. Branch names must start with 'PI' followed by a number."
            exit 1
          fi
      - name: Require Code Review Approval
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            pull_number=$(jq --raw-output .pull_request.number "${{ github.event_path }}")
            response=$(curl -s -X GET \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.PI_CODE_REVIEW }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${pull_number}/reviews")
            approvals=$(echo "$response" | jq '[.[] | select(.state == "APPROVED")] | length')
            author=$(jq --raw-output .pull_request.user.login "${{ github.event_path }}")
            if [[ "$approvals" -lt 1 ]]; then
              echo "At least one code review approval is required before merging."
              exit 1
            fi
            if [[ "${{ github.actor }}" == "$author" ]]; then
              echo "The branch author is not allowed to merge the pull request."
              exit 1
            fi
          fi
